//! `chefer init [dir]` — 產生帶繁中註解的 appcipe.yml 範本（不覆蓋既有檔案）。

use std::path::Path;

use anyhow::{Context, Result, bail};
use owo_colors::OwoColorize;

/// appcipe.yml 範本（精簡可執行；風格參考 examples/appcipe_simple.yml / appcipe.yml）。
/// 範本本身必須可被 `appcipe_normalize::load` 解析通過（image 路徑允許尚不存在，
/// load 不讀 image 檔，build 時才會讀）。
pub const APPCIPE_TEMPLATE: &str = r#"# ============================================================
#  appcipe.yml — Chefer application recipe (generated by `chefer init`)
#  Next steps:
#    1) Export an image tar with `docker save -o images/app.tar <image>`
#    2) `chefer check` to validate the configuration
#    3) `chefer build` to package into a single executable
# ============================================================

version: "0.1"          # Required: config format version (currently fixed at "0.1")

name: MyApp             # Required: application name; also used as the output file name and folder name
                        #   Rules: [A-Za-z][A-Za-z0-9_-]*, up to 64 characters
app_version: "0.1.0"    # Optional: application version (display only, does not affect packaging)

# data_dir: "D:/Apps/MyApp"   # Optional: override the default data directory location
# old_names: ["MyOldApp"]     # Optional: list of old folder names; data is migrated automatically on first launch

services:

  app:                  # Service name; rules: [a-z][a-z0-9_]*, up to 32 characters
    # Required: container image source (Docker/OCI image tar, may be relative to this file)
    image: ./images/app.tar

    # cmd: ["./start"]              # Optional: override the image's Cmd (string or array)
    # workdir: /app                 # Optional: working directory inside the container
    # env:                          # Optional: environment variables
    #   LOG_LEVEL: "info"

    # persist_path: /var/lib/app    # Optional: path inside the container to persist (absolute path)

    ports: ["8080:8080"]            # Optional: port mapping "host:guest[/proto]" (defaults to tcp)

    # mounts:                       # Optional: bind a host folder "<host path>:<container path>"
    #   - ./data:/mnt/data

    interface_mode: none            # Optional: gui | terminal | both | none (defaults to none)

    # depends_on: []                # Optional: other services this one depends on (determines startup order)
"#;

/// 在 `dir`（預設目前目錄）產生 appcipe.yml 範本；檔案已存在時報錯不覆蓋。
pub fn cmd_init(dir: Option<&Path>) -> Result<()> {
    let dir = dir.unwrap_or_else(|| Path::new("."));
    let path = dir.join("appcipe.yml");
    if path.exists() {
        bail!(
            "file already exists: {}; `chefer init` will not overwrite an existing file. \
             To regenerate the template, remove or rename that file first",
            path.display()
        );
    }
    std::fs::create_dir_all(dir)
        .with_context(|| format!("failed to create directory: {}", dir.display()))?;
    std::fs::write(&path, APPCIPE_TEMPLATE)
        .with_context(|| format!("failed to write template: {}", path.display()))?;

    println!(
        "{}  {}",
        "✔ Template created".green().bold(),
        path.display().to_string().blue()
    );
    println!(
        "{}",
        "Next: edit appcipe.yml (update name and image paths) → `chefer check` → `chefer build`"
            .dimmed()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 範本必須可被正式載入入口（appcipe_normalize::load）解析與驗證通過。
    /// load 不讀 image 檔，故範本中指向不存在的 tar 路徑沒有問題。
    #[test]
    fn template_passes_normalize_load() {
        let dir = tempfile::tempdir().unwrap();
        cmd_init(Some(dir.path())).unwrap();

        let path = dir.path().join("appcipe.yml");
        let app = appcipe_normalize::load(&path).expect("init 範本應通過 load");
        assert_eq!(app.name, "MyApp");
        assert_eq!(app.version, "0.1");
        assert!(app.services.contains_key("app"));
        // host 路徑應已被 normalize 絕對化
        match &app.services["app"].image {
            appcipe_spec::ImageSourceOrPath::TarPath(p) => {
                assert!(Path::new(p).is_absolute(), "image 路徑應為絕對：{p}");
            }
            other => panic!("非預期的 image 形式：{other:?}"),
        }
    }

    /// 已存在的 appcipe.yml 不可被覆蓋。
    #[test]
    fn refuses_to_overwrite_existing_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("appcipe.yml");
        std::fs::write(&path, "original").unwrap();

        let err = cmd_init(Some(dir.path())).unwrap_err().to_string();
        assert!(err.contains("already exists"), "{err}");
        // 原內容不可被動到
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "original");
    }

    /// 目標目錄不存在時會自動建立。
    #[test]
    fn creates_missing_directory() {
        let dir = tempfile::tempdir().unwrap();
        let sub = dir.path().join("a/b");
        cmd_init(Some(&sub)).unwrap();
        assert!(sub.join("appcipe.yml").is_file());
    }
}
