[package]
name = "appcipe-spec"
version = "0.1.0"     # 這個版本號前兩位跟隨 appcipe.yml 版本
edition = "2024"

[dependencies]
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
