[package]
name = "vmm-backend"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
chefer-bundle = { version = "0.3.0", path = "../chefer-bundle" }
guest-agent = { version = "0.3.0", path = "../guest-agent" }
sha2 = "0.11.0"
tar = "0.4.46"

[target."cfg(windows)".dependencies]
tempfile = "3.27.0"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_LibraryLoader", "Win32_System_Threading"] }

[dev-dependencies]
serde_json = "1.0.145"
tempfile = "3.27.0"
