[package]
name = "chefer-runtime"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1"
hex = "0.4"
tempfile = "3"
zstd = "0.13"
tar = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
clap = { version = "4.0", features = ["derive"] }
fs-err = "3.3.0"
sha2 = "0.11.0"
ctrlc = "3.5.2"
chefer-bundle = { version = "0.2.0", path = "../chefer-bundle" }
vmm-backend = { version = "0.2.0", path = "../vmm-backend" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_UI_WindowsAndMessaging",
] }
